[ bots ]
  [ bots.discord ]
  token = "REDACTED"
  enabled=true

  [ bots.telegram ]
  token="REDACTED"
  enabled=true

[ database ]
path = "linkmc.db"
# this is used for verifying that requests are coming from our servers
auth_token = "something super secret and secure that no one can guess"

[ twitter ]
api_key="ethan is a fucking loser"
api_secret=""

[ web ]
host="localhost:8080"
callback_path="/verify"

[ discord ]
channel="verify"